### ISSUE TITLE
unable to go get minigo: undefined: internalRuntimeCode

### ISSUE THREAD

**Issue by mewmew** [DQNEO/minigo#1]
Hi @DQNEO!

The mini Go compiler looks like a very interesting project. I wanted to take it out for a spin, but ran into the follow error when running `go get`:

```
u@x1 ~> go get github.com/DQNEO/minigo
# github.com/DQNEO/minigo
goget/src/github.com/DQNEO/minigo/main.go:106:54: undefined: internalRuntimeCode
goget/src/github.com/DQNEO/minigo/main.go:118:14: undefined: stdPkgs
```

Cheers,
Robin

**Comment by DQNEO** [comment]
Thanks for reporting.
`go get` does not work for now, so can you clone this repo by git command ?

**Comment by mewmew** [comment]
Thanks. I used `git clone` followed by `make`. That worked well. Got the first test case running, really cool to see it work :)

```
u@x1 ~/D/m/minigo> ./minigo t/argv/argv.go > foo.s
u@x1 ~/D/m/minigo> as -o foo.o foo.s
u@x1 ~/D/m/minigo> clang -o foo foo.o
u@x1 ~/D/m/minigo> ./foo hello world
3
hello
```

I'll leave this issue open for now. Feel free to close it if you do not intend to make minigo `go get`able. Otherwise, close it once minigo is `go get`able. That way it is easier to get started with the project for outside contributors.

Happy hacking!

Cheers,
Robin

**Comment by mewmew** [comment]
Haha, too quick on the buttons. Re-opening.

**Comment by DQNEO** [comment]
I've spent one hour in trying to fix this, but in the end I've found it's not an easy task. 
A kind of deep-seated problems regarding self-hosting things.

Let me close this.
